{% import "context.j2" as ctx with context -%}

image: zhangxianbing/python-runtime:v0.0.1-59c3b60

stages:
  - test
  - deploy

variables:
  # git clone in Gitlab CI. https://stackoverflow.com/a/55216745/14504212
  GLOBAL_GIT_CONFIG: url."https://gitlab-ci-token:${CI_JOB_TOKEN}@{{ ctx.platform_url[8:] }}".insteadOf "{{ ctx.platform_url }}"

.common-before-script: &common-before-script
  before_script:
    - git config --global $GLOBAL_GIT_CONFIG
    - poetry config virtualenvs.in-project true

################################################################################
### Test
################################################################################

py_test:
  <<: *common-before-script
  stage: test
  retry: 2
  before_script:
    - git config --global $GLOBAL_GIT_CONFIG
    - poetry config virtualenvs.in-project true
  script:
    - poetry install --with test -vv
    - source .venv/bin/activate
    - make test

################################################################################
### Deploy
################################################################################

pages:
  <<: *common-before-script
  stage: deploy
  script:
    - poetry install --with doc -vv
    - source .venv/bin/activate
    - make build-doc
  artifacts:
    paths:
      - public
