# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake [core]
        types: [python]
        args: [-i, --remove-all-unused-imports, --ignore-init-module-imports]
        files: src/.*|tests/.*

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        types: [python]
        args: [--lines-after-imports, "-1"]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        exclude: tests/
        additional_dependencies:
          - types-click
