name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: 单元测试

    strategy:
      matrix:
        python-versions: [3.6, 3.7, 3.8, 3.9, 3.10]
        os: [ubuntu-20.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: 拉取代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install -E test
          poetry shell

      - name: 测试
        run: pytest tests
